version: "3"

tasks:
  default:
    - task: help

  help:
    silent: true
    cmds:
      - task -l

  dev:
    desc: 開発ビルド
    cmds:
      - npm run tauri dev

  check:
    desc: cargo check
    dir: ./src-tauri
    cmds:
      - cargo check

  build:
    desc: 製品ビルド
    cmds:
      - npm run tauri build

  release:
    desc: |
      Build
          ∟ [Ex] task release VERSION=1.2.3
    cmds:
      - git checkout release
      - git rebase origin/master
      - |
        sed -i -r 's/\"version\": \".+\"/\"version\": \"{{.VERSION}}\"/g' src-tauri/tauri.conf.json
      - git add src-tauri/tauri.conf.json
      - git commit -m "v{{.VERSION}}"
      - git push
      - git checkout master
      - git pull
      - git merge --no-ff release
      - git push
    preconditions:
      - sh: "[ {{.VERSION}} != '' ]"
        msg: "VERSION is required."
